#! /bin/sh

xmes() {
    sh -c 'while fortune -s | \
       col -x | \
       xmessage -center -buttons Done:1,Another:0 -default Done -file - ; \
       do :; \
       done'
   }

zeni() {
    sh -c 'while fortune -s | \
       col -x | \
       zenity --info --text "$(fortune -s | col -x)" --icon org.xfce.ristretto --title "Fortune Cookie:" --ok-label="Another" --extra-button="Enough" ; \
       do :; \
       done'
   }

kded() {
    sh -c `while kdialog \
       --icon "face-wink" --title "Fortune" \
       --no-label "Enough" --yes-label "Another" \
       --warningyesno "$(fortune)"; \
       do :; \
       done`
   }

# We go from exotic toward commonplace options:
if [[ -x `which zenity` ]]; then
    zeni ; exit 0
fi
if [[ -x `which kdialog` ]]; then
    kded ; exit 0
fi
if [[ -x `which xmessage` ]]; then
    xmes ; exit 0
fi
